### ISSUE TITLE
glyphicons are not appearing or displayed.

### ISSUE THREAD

**Issue by ayaanraj** [formio/aurelia-formio#1]
Hi there,
You are creating awesome things and doing fabulous job.
I somehow  implement the example in esnext, originally written in typescript.
So, here the problem is glypicons are not displayed as shown in the below image,and throws error as shown below:

![formio-test](https://user-images.githubusercontent.com/29095142/42640607-4bb63f98-8610-11e8-8f29-a27b1262bbad.png)

And, there are so many things in form builder, how I can customise them, as per requirement, could you provide some details.

**Comment by randallknutson** [comment]
Looks like you need to include the fontawesome files in your build process somewhere. This is custom to how you handle the build process.

Here is some information on how to customize the builder: http://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by Daedrias** [comment]
In several places in the code there is this :
if (!this.options.icons || this.options.icons === 'glyphicon') {

So to make the form builder use the fontawesome icons, you need to add this :
Formio.builder(document.getElementById('vdm-formio-builder'),
    'url to the form',
    **{icons: 'fontawesome'}**
    );

Well actually you just need to add the icons attribute to your options. But icons: 'yolo. is not really serious.
